import React, { useState } from 'react';
import { ClinicalReport, PatientProfile } from '../../types';
import { 
  Printer, 
  Download, 
  Copy, 
  Check, 
  FileCode, 
  X, 
  CheckCircle2,
  FileText
} from 'lucide-react';
import { jsPDF } from 'jspdf';

interface ReportExportModalProps {
  report: ClinicalReport;
  patient: PatientProfile;
  isOpen: boolean;
  onClose: () => void;
}

export const ReportExportModal: React.FC<ReportExportModalProps> = ({
  report,
  patient,
  isOpen,
  onClose
}) => {
  const [copied, setCopied] = useState(false);
  const [exportType, setExportType] = useState<'soap' | 'json' | 'summary'>('soap');

  if (!isOpen) return null;

  const soapText = `CLINICAL VOICE ENCOUNTER NOTE (SOAP)
=====================================================
Patient: ${patient.name} (Age: ${patient.age}, Gender: ${patient.gender})
Encounter Date: ${new Date(report.generatedAt).toLocaleString()}
Primary Physician: ${patient.primaryPhysician.name}
Session Mode: ${report.sessionMode}

[SUBJECTIVE]
${report.soapNote.subjective}

[OBJECTIVE]
${report.soapNote.objective}

[ASSESSMENT]
${report.soapNote.assessment}

[PLAN & ACTION ITEMS]
${report.soapNote.plan}

RED FLAGS IDENTIFIED (${report.redFlags.length}):
${report.redFlags.map(f => `- [${f.category.toUpperCase()}] ${f.title}: ${f.description} (Action: ${f.recommendedAction})`).join('\n') || 'None'}

YELLOW FLAGS FOR MONITORING (${report.yellowFlags.length}):
${report.yellowFlags.map(f => `- [${f.category.toUpperCase()}] ${f.title}: ${f.description}`).join('\n') || 'None'}

PATIENT QUESTIONS FOR CLINICIAN:
${report.patientConcernsForDoctor.map(q => `- ${q}`).join('\n')}
=====================================================
Generated by CareVoice AI Geriatric Voice Triage System`;

  const jsonText = JSON.stringify(report, null, 2);

  const handleCopy = () => {
    const textToCopy = exportType === 'json' ? jsonText : soapText;
    navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    
    // Header
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.setTextColor(13, 148, 136); // Teal
    doc.text('CareVoice.AI - Clinician Encounter Report', 14, 20);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text(`Generated: ${new Date(report.generatedAt).toLocaleString()}`, 14, 26);
    doc.text(`Patient: ${patient.name} | Age: ${patient.age} | PCP: ${patient.primaryPhysician.name}`, 14, 32);

    doc.line(14, 36, 196, 36);

    let currentY = 44;

    // Overview
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text('1. PATIENT OVERVIEW & WELLBEING', 14, currentY);
    currentY += 6;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(51, 65, 85);
    const overviewLines = doc.splitTextToSize(report.patientOverview.summary, 180);
    doc.text(overviewLines, 14, currentY);
    currentY += overviewLines.length * 5 + 6;

    // SOAP
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text('2. SOAP CLINICAL DOCUMENTATION', 14, currentY);
    currentY += 6;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text('Subjective:', 14, currentY);
    currentY += 5;
    doc.setFont('helvetica', 'normal');
    const subjLines = doc.splitTextToSize(report.soapNote.subjective, 180);
    doc.text(subjLines, 14, currentY);
    currentY += subjLines.length * 5 + 4;

    doc.setFont('helvetica', 'bold');
    doc.text('Objective:', 14, currentY);
    currentY += 5;
    doc.setFont('helvetica', 'normal');
    const objLines = doc.splitTextToSize(report.soapNote.objective, 180);
    doc.text(objLines, 14, currentY);
    currentY += objLines.length * 5 + 4;

    doc.setFont('helvetica', 'bold');
    doc.text('Assessment:', 14, currentY);
    currentY += 5;
    doc.setFont('helvetica', 'normal');
    const assLines = doc.splitTextToSize(report.soapNote.assessment, 180);
    doc.text(assLines, 14, currentY);
    currentY += assLines.length * 5 + 4;

    doc.setFont('helvetica', 'bold');
    doc.text('Plan & Recommendations:', 14, currentY);
    currentY += 5;
    doc.setFont('helvetica', 'normal');
    const planLines = doc.splitTextToSize(report.soapNote.plan, 180);
    doc.text(planLines, 14, currentY);
    currentY += planLines.length * 5 + 6;

    // Flags
    if (report.redFlags.length > 0) {
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(225, 29, 72); // Red
      doc.text('3. RED FLAGS REQUIRING IMMEDIATE ATTENTION', 14, currentY);
      currentY += 6;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      report.redFlags.forEach(rf => {
        const flagText = `• [${rf.category.toUpperCase()}] ${rf.title}: ${rf.description} -> ACTION: ${rf.recommendedAction}`;
        const flagLines = doc.splitTextToSize(flagText, 180);
        doc.text(flagLines, 14, currentY);
        currentY += flagLines.length * 5 + 2;
      });
    }

    doc.save(`CareVoice_Clinical_Report_${patient.name.replace(' ', '_')}.pdf`);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
      <div className="bg-white rounded-3xl max-w-2xl w-full p-6 sm:p-8 shadow-2xl border border-slate-200 text-slate-900 max-h-[90vh] flex flex-col">
        
        {/* Header */}
        <div className="flex items-center justify-between pb-4 border-b border-slate-200">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-teal-100 text-teal-700 flex items-center justify-center">
              <FileText className="w-6 h-6" />
            </div>
            <div>
              <h3 className="text-xl font-bold text-slate-900">
                Export Clinician Report
              </h3>
              <p className="text-xs text-slate-500">
                SOAP Note & EHR Integration Ready
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 text-slate-400 hover:text-slate-600 rounded-xl hover:bg-slate-100"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Format Selector */}
        <div className="flex items-center gap-2 my-4">
          <button
            onClick={() => setExportType('soap')}
            className={`px-3 py-1.5 rounded-xl text-xs font-bold transition ${
              exportType === 'soap' ? 'bg-teal-600 text-white shadow-sm' : 'bg-slate-100 text-slate-700 hover:bg-slate-200'
            }`}
          >
            SOAP Clinical Note
          </button>
          <button
            onClick={() => setExportType('json')}
            className={`px-3 py-1.5 rounded-xl text-xs font-bold transition ${
              exportType === 'json' ? 'bg-teal-600 text-white shadow-sm' : 'bg-slate-100 text-slate-700 hover:bg-slate-200'
            }`}
          >
            EHR JSON Schema
          </button>
        </div>

        {/* Content Preview */}
        <div className="flex-1 overflow-y-auto bg-slate-900 text-slate-100 p-4 rounded-2xl font-mono text-xs leading-relaxed border border-slate-800 my-2 whitespace-pre-wrap">
          {exportType === 'json' ? jsonText : soapText}
        </div>

        {/* Action Footer */}
        <div className="flex items-center justify-between gap-3 pt-4 border-t border-slate-200 mt-2">
          <button
            onClick={() => window.print()}
            className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold text-xs border border-slate-300 transition"
          >
            <Printer className="w-4 h-4" />
            <span>Print Report</span>
          </button>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-slate-100 hover:bg-teal-50 text-slate-800 font-bold text-xs border border-slate-300 transition"
            >
              {copied ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4 text-teal-600" />}
              <span>{copied ? 'Copied to Clipboard!' : 'Copy to Clipboard'}</span>
            </button>

            <button
              onClick={handleDownloadPDF}
              className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-teal-600 hover:bg-teal-700 text-white font-bold text-xs shadow-md transition"
            >
              <Download className="w-4 h-4" />
              <span>Download PDF Note</span>
            </button>
          </div>
        </div>

      </div>
    </div>
  );
};
